### ISSUE TITLE
请问下有文档介绍或者可以在源码里加写注释吗？

### ISSUE THREAD

**Issue by xianrui** [SeriaWei/EasyFrameWork#1]
想了解学习一下。下来发现没有注释没有文档，希望能提供一点，感谢分享。

**Comment by SeriaWei** [comment]
一直想写确没有时间，之前有简单的写了一些不是很多可能帮助有限。
[http://blog.zkea.net/category/easyframework/](http://blog.zkea.net/category/easyframework/)
另外WIKI里面也有写了一些：
[http://blog.zkea.net/category/easyframework/](https://github.com/SeriaWei/EasyFrameWork/wiki)

因为一直在忙其它事情，都没时间完尚文档。
